---
Name: CIBridge
After:
  - 'mysite'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
CIBridge:
  autoload:
    libraries:
      config: CI_Config
